name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image timestamp tag
        id: vars
        run: |
          echo "IMAGE_TAG=$(TZ=Asia/Kolkata date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "GHCR_IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          echo "DOCKERHUB_IMAGE_REPO=saicharancodes/araku-trails-images" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            saicharancodes/araku-trails-images

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.vars.outputs.GHCR_IMAGE_REPO }}:${{ steps.vars.outputs.IMAGE_TAG }}
            ${{ steps.vars.outputs.DOCKERHUB_IMAGE_REPO }}:${{ steps.vars.outputs.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
